app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['as' => 'films::'], function() {
    // autocomplete json
    Route::get('/films/ajax_search', [
        'as' => 'ajax_search',
        'uses' => 'FilmController@ajaxSearch'
    ]);
    // All films
    Route::get('/', [
        'as' => 'all',
        'uses' => 'FilmController@index'
    ]);
    // Add film
    Route::get('films/add', [
        'as' => 'create',
        'uses' => 'FilmController@create'
    ]);
    // Store film
    Route::post('films/add', [
        'as' => 'store',
        'uses' => 'FilmController@store'
    ]);
    // Search films
    Route::get('films/search', [
        'as' => 'search',
        'uses' => 'FilmController@search'
    ]);
    // Show film
    Route::get('films/{id}', [
        'as' => 'show',
        'uses' => 'FilmController@show'
    ]);
    // Edit film
    Route::get('films/{id}/edit', [
        'as' => 'edit',
        'uses' => 'FilmController@edit'
    ]);
    // Update film
    Route::put('films/{id}', [
        'as' => 'update',
        'uses' => 'FilmController@update'
    ]);
    // Remove film
    Route::delete('films/{id}', [
        'as' => 'remove',
        'uses' => 'FilmController@destroy'
    ]);
});

Route::group(['as' => 'catalogs::'], function() {
    // All
    Route::get('/catalogs', [
        'as' => 'all',
        'uses' => 'CatalogController@index'
    ]);
    // Add
    Route::get('catalogs/add', [
        'as' => 'create',
        'uses' => 'CatalogController@create'
    ]);
    // Store
    Route::post('catalogs/add', [
        'as' => 'store',
        'uses' => 'CatalogController@store'
    ]);
    // // Show
    Route::get('catalogs/{id}', [
        'as' => 'show',
        'uses' => 'CatalogController@show'
    ]);
    // Edit
    Route::get('catalogs/{id}/edit', [
        'as' => 'edit',
        'uses' => 'CatalogController@edit'
    ]);
    // // Update
    Route::put('catalogs/{id}', [
        'as' => 'update',
        'uses' => 'CatalogController@update'
    ]);
    // // Remove
    Route::delete('catalogs/{id}', [
        'as' => 'remove',
        'uses' => 'CatalogController@destroy'
    ]);
});

Route::group(['as' => 'genres::'], function() {
    // All
    Route::get('/genres', [
        'as' => 'all',
        'uses' => 'GenreController@index'
    ]);
    // Add
    Route::get('genres/add', [
        'as' => 'create',
        'uses' => 'GenreController@create'
    ]);
    // Store
    Route::post('genres/add', [
        'as' => 'store',
        'uses' => 'GenreController@store'
    ]);
    // // Show
    Route::get('genres/{id}', [
        'as' => 'show',
        'uses' => 'GenreController@show'
    ]);
    // Edit
    Route::get('genres/{id}/edit', [
        'as' => 'edit',
        'uses' => 'GenreController@edit'
    ]);
    // // Update
    Route::put('genres/{id}', [
        'as' => 'update',
        'uses' => 'GenreController@update'
    ]);
    // // Remove
    Route::delete('genres/{id}', [
        'as' => 'remove',
        'uses' => 'GenreController@destroy'
    ]);
});

Route::group(['as' => 'countries::'], function() {
    // All
    Route::get('/countries', [
        'as' => 'all',
        'uses' => 'CountryController@index'
    ]);
    // Add
    Route::get('countries/add', [
        'as' => 'create',
        'uses' => 'CountryController@create'
    ]);
    // Store
    Route::post('countries/add', [
        'as' => 'store',
        'uses' => 'CountryController@store'
    ]);
    // // Show
    Route::get('countries/{id}', [
        'as' => 'show',
        'uses' => 'CountryController@show'
    ]);
    // Edit
    Route::get('countries/{id}/edit', [
        'as' => 'edit',
        'uses' => 'CountryController@edit'
    ]);
    // // Update
    Route::put('countries/{id}', [
        'as' => 'update',
        'uses' => 'CountryController@update'
    ]);
    // // Remove
    Route::delete('countries/{id}', [
        'as' => 'remove',
        'uses' => 'CountryController@destroy'
    ]);
});

Route::group(['as' => 'people::'], function() {
    // autocomplete json
    Route::get('/people/ajax_search', [
        'as' => 'ajax_search',
        'uses' => 'PersonController@ajaxSearch'
    ]);
    // All
    Route::get('/people', [
        'as' => 'all',
        'uses' => 'PersonController@index'
    ]);
    // Add
    Route::get('people/add', [
        'as' => 'create',
        'uses' => 'PersonController@create'
    ]);
    // Store
    Route::post('people/add', [
        'as' => 'store',
        'uses' => 'PersonController@store'
    ]);
    // // Show
    Route::get('people/{id}', [
        'as' => 'show',
        'uses' => 'PersonController@show'
    ]);
    // Edit
    Route::get('people/{id}/edit', [
        'as' => 'edit',
        'uses' => 'PersonController@edit'
    ]);
    // // Update
    Route::put('people/{id}', [
        'as' => 'update',
        'uses' => 'PersonController@update'
    ]);
    // // Remove
    Route::delete('people/{id}', [
        'as' => 'remove',
        'uses' => 'PersonController@destroy'
    ]);
});

app/Film.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    protected $fillable = ['name', 'description', 'year', 'rating', 'kinopoisk_id', 'original_name'];

    public function getPosterAttribute($value)
    {
        if (!($this->attributes['kinopoisk_id'])) {
            $poster = '//st.kp.yandex.net/images/movies/poster_none.png';
        } else {
            $poster = '//st.kp.yandex.net/images/film_big/' . $this->attributes['kinopoisk_id'] . '.jpg';
        }

        return $poster;
    }

    public function getKinopoiskLinkAttribute($value)
    {
        $link = '//kinopoisk.ru/film/' . $this->attributes['kinopoisk_id'] . '/';

        return $link;
    }

    public function getYearAttribute($value) {
        if ($value == 0) {
            return '';
        }
        else {
            return $value;
        }
    }

    /**
     * Убираем пробелы из имени
     */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = trim($value);
    }

    /**
     * Жанры фильма
     */
    public function genres()
    {
        return $this->belongsToMany('App\Genre');
    }

    /**
     * Режиссеры фильма
     */
    public function directors()
    {
        return $this->belongsToMany('App\Person', 'director_film');
    }

    /**
     * Актеры фильма
     */
    public function actors()
    {
        return $this->belongsToMany('App\Person', 'actor_film');
    }

    /**
     * Каталоги, в которые входит фильм
     */
    public function catalogs()
    {
        return $this->belongsToMany('App\Catalog');
    }

    /**
     * Страны, к которым принадлежит фильм
     */
    public function countries()
    {
        return $this->belongsToMany('App\Country');
    }

}

resources/views/_film.blade.php
<div class="panel panel-default">
    <div class="panel-body">
        <div class="media">
            <div class="media-left">
                <p><img class="media-object" src="{{ $film->poster }}" alt="" width="100"></p>
                @if($film->rating == 1)
                    <span class="btn btn-xs btn-success" title="Понравился"><i class="fa fa-thumbs-up"></i></span>
                @elseif ($film->rating == 2)
                    <span class="btn btn-xs btn-warning" title="Не просмотрен"><i class="fa fa-eye-slash"></i></span>
                @elseif ($film->rating == 0)
                    <span class="btn btn-xs btn-danger" title="Не понравился"><i class="fa fa-thumbs-down"></i></span>
                @endif
                <a href="{{ route('films::edit', ['id' => $film->id]) }}" class="btn btn-default btn-xs" title="Редактировать"><i class="fa fa-pencil"></i></a>
                @if($film->kinopoisk_id)
                    <a href="{{ $film->kinopoisk_link }}" class="btn btn-primary btn-xs" target="_blank"><i class="fa fa-film"></i></a>
                @endif
            </div>
            <div class="media-body">
                <div class="col-md-12">
                    <h4 class="media-heading">
                        <strong>
                            <a href="{{ route('films::show', ['id' => $film->id]) }}">
                                {{ $film->name }}
                            </a>
                        </strong>
                    </h4>
                    <p class="text-muted">{{ $film->year }}</p>
                    <p>
                        @foreach($film->countries as $country)
                            <span class="label label-primary"><a href="{{ route('countries::show', ['id' => $country->id]) }}"><i class="fa fa-globe"></i> {{ $country->name }}</a></span>
                        @endforeach
                    </p>
                    <p>
                        @foreach($film->genres as $genre)
                            <span class="label label-success"><a href="{{ route('genres::show', ['id' => $genre->id]) }}"><i class="fa fa-tag"></i> {{ $genre->name }}</a></span>
                        @endforeach
                    </p>
                    <p>
                        @foreach($film->catalogs as $catalog)
                            <span class="label label-warning"><a href="{{ route('catalogs::show', ['id' => $catalog->id]) }}"><i class="fa fa-folder-open-o"></i> {{ $catalog->name }}</a></span>
                        @endforeach
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/app.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta>
        <title>Kinobase</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600,300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
        <link rel="stylesheet" href="/assets/css/font-awesome.min.css">
        <link rel="stylesheet" href="/assets/css/magnific-popup.css">
        <link rel="stylesheet" href="/assets/css/select2.min.css">
        <link rel="stylesheet" href="/assets/css/easy-autocomplete.min.css">
        <link rel="stylesheet" href="/assets/css/easy-autocomplete.themes.min.css">
        <link rel="stylesheet" href="/assets/css/main.css">
    </head>
    <body>
        <div class="container-fluid">
            <div class="container">
                <div class="row header">
                    <div class="col-md-5">
                        <h1><a href="/">Kinobase</a></h1>
                    </div>
                    <div class="col-md-7">
                        <a href="{{ route('films::all') }}" class="btn btn-xs btn-default">Фильмы</a>
                        <a href="{{ route('catalogs::all') }}" class="btn btn-xs btn-default">Каталоги</a>
                        <a href="{{ route('genres::all') }}" class="btn btn-xs btn-default">Жанры</a>
                        <a href="{{ route('countries::all') }}" class="btn btn-xs btn-default">Страны</a>
                        <a href="{{ route('people::all') }}" class="btn btn-xs btn-default">Люди</a>
                    </div>
                </div>
                <div class="row breadcrumbs">
                    <div class="col-md-12">
                        @yield('breadcrumbs')
                    </div>
                </div>
                <div class="content">
                    @yield('content')
                </div>
            </div>
        </div>
        <script src="//yastatic.net/jquery/2.1.4/jquery.min.js"></script>
        <script src="//yastatic.net/underscore/1.6.0/underscore-min.js"></script>
        <script src="//yastatic.net/backbone/1.1.2/backbone-min.js"></script>
        <script src="/assets/js/jquery.magnific-popup.min.js"></script>
        <script src="/assets/js/jquery.are-you-sure.js"></script>
        <script src="/assets/js/select2.min.js"></script>
        <script src="/assets/js/select2.ru.js"></script>
        <script src="/assets/js/jquery.easy-autocomplete.min.js"></script>
        <script src="/assets/js/main.js"></script>
    </body>
</html>